### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by KUBAHO3** [Bestbynature/awesome-books-project#3]
In this project, you have done very well and I appreciate your effort to make it look more awesome for the users!
Though we are raising this issue for you to go back through it and refine it in a better way! so please consider the following:

- [x] Please as the UI requirement consider making the active nav identified among others by giving it different colors so that the user will be able to know the active section!
- [x] Againg as appearing in the given wireframes, please consider making the footer fixed on the bottom of the page to prevent extra space or gap after the contents on the screen.
- [x]  Apply the second issue raised to the header as well!

**Comment by Bestbynature** [comment]
Thanks for the points raised.
